name: CI

on: 
  schedule:
    - cron: "0 5 * * *" # Every day at 5:00

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install nbval
    - name: Test all Notebooks
      run: pytest --nbval-lax -v *.ipynb
