name: Test all Notebooks

on: 
  schedule:
    - cron: "0 5 * * *" # Every day at 5:00

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install nbval
    - name: Test all Notebooks
      run: pytest --nbval-lax -v *.ipynb
